name: Build and Deploy Python App to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        working-directory: my-flask-app
        run: |
          source venv/bin/activate
          pytest
          
      - name: Package app for deployment
        run: |
          cd my-flask-app
          zip -r ../release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Set Publish Profile Authentication using ZIP Deploy
        run: |
          # Write Publish Profile content to a file
          echo "${{ secrets.AZURE_APP_PUBLISH_PROFILE }}" > publish-profile.publishsettings
          
          # Extract username and password from the Publish Profile
          export AZURE_USERNAME=$(grep -oPm1 "(?<=<userName>)[^<]+" publish-profile.publishsettings)
          export AZURE_PASSWORD=$(grep -oPm1 "(?<=<userPWD>)[^<]+" publish-profile.publishsettings)
          export AZURE_PUBLISH_URL=$(grep -oPm1 "(?<=<publishUrl>)[^<]+" publish-profile.publishsettings)

          # Authenticate using the extracted credentials
          az login --username "$AZURE_USERNAME" --password "$AZURE_PASSWORD"
          
      - name: Deploy to Azure Function App using ZipDeploy
        run: |
          # Deploy to Azure using ZipDeploy method
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./release.zip \
            --publish-profile publish-profile.publishsettings
