name: Build and Deploy Python App to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allow reading repository contents

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (optional but recommended)
      - name: Run tests
        working-directory: my-flask-app
        run: |
          source venv/bin/activate
          pytest

      # Step 5: Package the app for deployment (creating a zip file)
      - name: Package app for deployment
        run: |
          cd my-flask-app
          zip -r ../release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      # Step 6: Upload the package as an artifact for later use
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      # Step 1: Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 2: Install Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash  # Installs Azure CLI

      # Step 3: Log in to Azure using Publish Profile
      - name: Log in to Azure using Publish Profile
        run: |
          # Save the publish profile from secrets to a file
          echo "${{ secrets.AZURE_APP_PUBLISH_PROFILE }}" > publish-profile.publishsettings
          
          # Authenticate with Azure Function App using the Publish Profile
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./release.zip \
            --publish-profile publish-profile.publishsettings

      # Step 4: Deploy the app to Azure Function App using ZipDeploy
      - name: Deploy to Azure Function App using ZipDeploy
        run: |
          # Deploy the zip file to the Azure Function App using the publish profile
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./release.zip \
            --publish-profile publish-profile.publishsettings
