name: Build and Deploy Python App to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: my-flask-app
        run: |
          source venv/bin/activate
          pytest

      - name: Package app for deployment
        run: |
          cd my-flask-app
          zip -r ../release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        with:
          azure-cli-version: '2.34.0'  # specify the version of the Azure CLI if necessary

      - name: Log in to Azure using Publish Profile
        run: |
          echo "${{ secrets.AZURE_APP_PUBLISH_PROFILE }}" > publish-profile.publishsettings
          
          # Directly authenticate using the publish profile file for the deployment
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./release.zip \
            --publish-profile publish-profile.publishsettings
          
      - name: Deploy to Azure Function App using ZipDeploy
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_FUNCTION_APP_NAME }} \
            --src ./release.zip \
            --publish-profile publish-profile.publishsettings
