name: Build, Test, and Upload Python Report to Azure Blob Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: my-flask-app
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests & generate report
        working-directory: my-flask-app
        run: |
          source venv/bin/activate
          pytest --junitxml=test-results.xml

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: my-flask-app/test-results.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Download test report artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: Upload test report to Azure Blob Storage
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
          name: python-test-report
          path: test-results.xml
